Pizzeria/Controllers/OrdineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pizzeria.Models;

namespace Pizzeria.Controllers
{
    public class OrdineController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Ordine
        public ActionResult Index()
        {
            var ordine = db.Ordine.Include(o => o.Pizza).Include(o => o.Utente);
            return View(ordine.ToList());
        }

        // GET: Ordine/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordine ordine = db.Ordine.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }
            return View(ordine);
        }

        // GET: Ordine/Create
        public ActionResult Create()
        {
            ViewBag.IdPizza = new SelectList(db.Pizza, "IDpizza", "NomePizza");
            ViewBag.IdUtente = new SelectList(db.Utente, "IDutente", "Nome");
            return View();
        }

        // POST: Ordine/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDordine,Quantita,Note,IndirizzoSpedizione,OrdineConsegnato,OrdineInConsegnato,DataOrdine,IdPizza,IdUtente")] Ordine ordine)
        {
            if (ModelState.IsValid)
            {
                db.Ordine.Add(ordine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdPizza = new SelectList(db.Pizza, "IDpizza", "NomePizza", ordine.IdPizza);
            ViewBag.IdUtente = new SelectList(db.Utente, "IDutente", "Nome", ordine.IdUtente);
            return View(ordine);
        }

        // GET: Ordine/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordine ordine = db.Ordine.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdPizza = new SelectList(db.Pizza, "IDpizza", "NomePizza", ordine.IdPizza);
            ViewBag.IdUtente = new SelectList(db.Utente, "IDutente", "Nome", ordine.IdUtente);
            return View(ordine);
        }

        // POST: Ordine/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDordine,Quantita,Note,IndirizzoSpedizione,OrdineConsegnato,OrdineInConsegnato,DataOrdine,IdPizza,IdUtente")] Ordine ordine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ordine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdPizza = new SelectList(db.Pizza, "IDpizza", "NomePizza", ordine.IdPizza);
            ViewBag.IdUtente = new SelectList(db.Utente, "IDutente", "Nome", ordine.IdUtente);
            return View(ordine);
        }

        // GET: Ordine/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Ordine ordine = db.Ordine.Find(id);
        //    if (ordine == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(ordine);
        //}

        // POST: Ordine/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Ordine ordine = db.Ordine.Find(id);
            db.Ordine.Remove(ordine);
            db.SaveChanges();
            return RedirectToAction("Carrello");
        }

        //------- Partila View Aggiungi al carrello-------------  
        public ActionResult PartialViewAggiungiAlCarrello()
        {
            return PartialView("_PartialViewAggiungiAlCarrello");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PartialViewAggiungiAlCarrello(Ordine ordine, int id)
        {
            if (ModelState.IsValid && ordine.Quantita>0)// se la quantita e maggiore di 0 vuol dire che ce un ordine
            {
                Utente utente=db.Utente.Where(x=>x.Username == User.Identity.Name).First();
                ordine.IndirizzoSpedizione = " ";
                ordine.IdPizza = id;
                ordine.IdUtente = utente.IDutente;
                db.Ordine.Add(ordine);
                db.SaveChanges();
                return RedirectToAction("Index","Pizza",null);
            }

            return RedirectToAction("Details","Pizza",db.Pizza.Find(id));
        }

        public ActionResult Carrello() {

        Utente utente=db.Utente.Where(x=>x.Username== User.Identity.Name).FirstOrDefault();
        
           List<Ordine> ListaOrdine=db.Ordine.Include(x=>x.Pizza).Where(x=>x.IdUtente==utente.IDutente).ToList();
            if (ListaOrdine.Count<=0) 
            {
                ViewBag.carrelloVuoto = "Carrello Vuoto";
            }
           
            return View(ListaOrdine);
        }

        //=============Conferma dell'ordine=====================
        public ActionResult PartialViewConfermaOrdine() { 

            return PartialView("_PartialViewConfermaOrdine"); 

        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult PartialViewConfermaOrdine(Ordine ordine) {

            if (ModelState.IsValid && ordine.IndirizzoSpedizione!=null)
            {
              Utente utente = db.Utente.Where(x => x.Username == User.Identity.Name).FirstOrDefault();
                List<Ordine> Carrello = db.Ordine.Where(x => x.IdUtente == utente.IDutente && x.OrdineInConsegnato == false).ToList();

                foreach (Ordine item in Carrello)
                {
                    item.IndirizzoSpedizione = ordine.IndirizzoSpedizione;
                    item.DataOrdine=DateTime.Now;
                    item.OrdineInConsegnato = true;
                   


                    db.Entry(ordine).State = EntityState.Modified;
                    db.SaveChanges();
                }

                 ViewBag.MessaggioConferma = "Ordine Confermato";
                return RedirectToAction("Index", "Pizza");

            }


            return PartialView("_PartialViewConfermaOrdine");
        }

        public ActionResult PartialViewOrdineInConsegna()
        {
            Utente utente=db.Utente.Where(x=>x.Username== User.Identity.Name).FirstOrDefault();
            List<Ordine>ListaOrdineInCosegna=db.Ordine.Where(u=>u.IdUtente==utente.IDutente && u.OrdineInConsegnato==false).ToList();

            return PartialView("_PartialViewOrdineInConsegna",ListaOrdineInCosegna);
        }

        public JsonResult TotOrdine()
        {
            //mi prendo l username
            Utente utente = db.Utente.Where(x => x.Username == User.Identity.Name).FirstOrDefault();
            
            List<Ordine> Carrello = db.Ordine.Where(x => x.IdUtente == utente.IDutente).ToList();
            decimal totOrdine = 0;
            if (utente!=null)
            {

                foreach (var item in Carrello)
                {

                    decimal prezzoItem = (item.Pizza.Prezzo * item.Quantita);
                    totOrdine += prezzoItem;
                }
                

            }
            return Json(totOrdine, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pizzeria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Content/style.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body class="m-0 p-0">
    <nav class="navbar navbar-expand-lg bg-danger">
        <div class="container-fluid align-items-center">
            <a class="navbar-brand text-white fs-1 fw-bold m-0" href="~/Home/Index">Pizzeria
                <img src="~/Content/img/logo.png" alt="Alternate Text" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center text-white" id="navbarNav">
                <ul class="navbar-nav mx-3">
                    @if(User.Identity.IsAuthenticated)
                    {

                    <li class="nav-item mx-3">
                        <a class="text-white" href="~/Pizza/ListaPizza">Gestione Ordine Pizze</a>
                    </li>
                     }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item mx-3">
                            <a class="text-white" href="~/Home/Logout" style="text-decoration:none;">Logout</a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item mx-3">
                            <a class="text-white" href="~/Home/Login" style="text-decoration: none;">Login</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                        {

                           <li class="nav-item mx-3">
                               @Html.ActionLink("Carrello", "Carrello", "Ordine", null, new { @class = "text-white me-2", style = "text-decoration:none;" })
                           </li>
                        }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Applicazione ASP.NET</p>
        </footer>
    </div>

</body>
</html>