Pizzeria/Controllers/HomeController.cs
using Pizzeria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Pizzeria.Controllers
{
    public class HomeController : Controller
    {
        private ModelDbContext db = new ModelDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Utente u)
        {
            if ( db.Utente.Where(x => x.Username == u.Username && x.Password == u.Password).Count() == 1)
            {
                FormsAuthentication.SetAuthCookie(u.Username, false);
                return Redirect(FormsAuthentication.DefaultUrl);
            }
            {
                ViewBag.Error = "Username e/o password errati.";
                return View();
            }
            

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect(FormsAuthentication.LoginUrl);
            
        }
    }
}

Pizzeria/Controllers/UtenteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pizzeria.Models;

namespace Pizzeria.Controllers
{
    public class UtenteController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Utente
        public ActionResult Index()
        {
            return View(db.Utente.ToList());
        }

        // GET: Utente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }
            return View(utente);
        }

        // GET: Utente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utente/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDutente,Nome,Cognome,Ruolo,Username,Password")] Utente utente)
        {
            if (ModelState.IsValid)
            {
                utente.Ruolo = "User";
                db.Utente.Add(utente);
                db.SaveChanges();
                return RedirectToAction("Login","Home",null);
            }

            return View(utente);
        }

        // GET: Utente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }
            return View(utente);
        }

        // POST: Utente/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDutente,Nome,Cognome,Ruolo,Username,Password")] Utente utente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(utente);
        }

        // GET: Utente/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }
            return View(utente);
        }

        // POST: Utente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utente utente = db.Utente.Find(id);
            db.Utente.Remove(utente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pizzeria/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Pizzeria/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pizzeria/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <h1>SEI NELLA INDEX DELLA HOME</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>*@

@*<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@
<div class="container d-flex flex-column">

    <div class="row mb-4">
        <div class="col col-6 d-flex flex-column justify-content-center align-items-center ">
            <p class="fst-italic align-items-center"style="font-weight:bold">
               " 
                Filastrocca della pizza
                la tristezza si esorcizza;
                già col solo suo profumo
                le amarezze manda in fumo! 
                <br />

                Con lei torna l’allegria
                la mestizia caccia via:
                non appena l’han davanti
                son felici tutti quanti!
                <br />
                Con prosciutto o carciofini,
                tonno, olive o salamini
                patatine, aglio, pancetta:
                tutti vogliono una fetta!
                <br />
                Lei soddisfa ogni palato
                da esigente a delicato:
                ricca di semplicità,
                di sapore, di bontà.
                (Oppure: marchio d’italianità)
                <br />
                Per lei tutti fan follie,
                son disposti a far pazzie.
                L’acquolina sempre attizza:
                nulla è meglio della pizza! "
            </p>
            <h1>Prenota ora la tua pizza</h1>
            <h2>48 ore di lievitazione</h2>
            <a class="btn text-white" href="~/Home/Login" style="text-decoration: none; background-color: #970C0A;">Ordina Adesso</a>
        </div>
        <div class="col col-6">
            <img src="~/Content/img/hero_pizza2.png" alt="Alternate Text" />
        </div>
    </div>
    <hr />
    <div class="d-flex justify-content-around gap-3 m-5">
        <div class="row">
            <div class="col-6">
                <img src="~/Content/img/immagine-frontPage.jpg" alt="Alternate Text" width="500px" />
                <p class="mt-2 fst-italic d-flex justify-content-center align-items-center">La nostra pizza ha una tradizione antichissima</p>
            </div>
            <div class="col-6 mt-lg-5">
                <img src="~/Content/img/pexels-vinicius-benedit-1082343.jpg" alt="Alternate Text" width="500px" />
                <p class="mt-2 fst-italic d-flex justify-content-center align-items-center">Pizze cotte a legna come vuole la tradizione</p>
            </div>
        </div>
    </div>

    <div class="row ">
        <div class="col-6 social2 d-flex align-items-center">
            <p>Seguici sui nostri social: <span><i class="bi bi-instagram mx-3"></i></span><span><i class="bi bi-facebook mx-3"></i></span><span><i class="bi bi-twitter mx-3"></i></span></p>
        </div>
        <div class="col-6 social d-flex align-items-center">
            <span class=" mx-5">email:simone@TestProva.com</span> <span>cell: 333-1234567</span> 
        </div>
    </div>

</div>

Pizzeria/Views/Home/Login.cshtml
@model Pizzeria.Models.Utente

@{
    ViewBag.Title = "Login";
}



<div class="container d-flex flex-column">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>non hai un account? @Html.ActionLink("Registrati", "Create","Utente")</p>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}